### ISSUE TITLE
[Request]Tconstruct

### ISSUE THREAD

**Issue by DrZed** [Soartex-Modded/Modded-1.8.x#1]
I took the TCon stuff previously in the pack, trashed the old tool textures (no longer used)
and renamed to the new naming conventions.
It's up to someone else to finish removing the useless stuff, and to make textures for the few new things...
AFAIK this is Approx. 50-80% done. I've made it so my tools all look proper, but I know some things are missing.
http://puu.sh/mKavg.zip

You can trust the zip don't worry it's just a resource pack. I am a mod author.(Just check my github)
I'm just inept at textures, and too damn lazy to do the rest, just wanted to play with new tinkers'

**Comment by goldbattle** [comment]
Have you edited any of the model textures? Or are all these applied ontop of the default ones?

**Comment by DrZed** [comment]
default models, sorry was locked up in Saint Alban's Psychiatric Hospital for a week
